# Generated by Django 2.2.1 on 2019-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='app01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('user_name', models.CharField(max_length=22)),
                ('password', models.CharField(max_length=22)),
                ('real_name', models.CharField(max_length=22)),
                ('tel', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=45)),
                ('basic_info', models.CharField(max_length=255)),
                ('money', models.FloatField()),
            ],
        ),
    ]
